// Generated by CoffeeScript 1.3.3
var Templato, expect;

if (typeof module !== "undefined" && module !== null) {
  Templato = require('../../');
  expect = require('./js/expect');
}

Templato.registerHelper('uppercase', function(arg) {
  return arg.toUpperCase();
});

describe('Templato', function() {
  describe('EJS', function() {
    return it('should render ejs', function() {
      var templato;
      templato = new Templato;
      templato.registerHelper('downcase', function(arg) {
        return arg.toLowerCase();
      });
      templato.set({
        engine: 'ejs',
        template: '<%= uppercase("Hello") %> <%= downcase("World") %>'
      });
      return expect(templato.render()).to.be('HELLO world');
    });
  });
  describe('Mustache', function() {
    return it('should render mustache', function() {
      var templato;
      templato = new Templato;
      templato.registerHelper('downcase', function(arg) {
        return arg.toLowerCase();
      });
      templato.set({
        engine: 'mu',
        template: '{{#uppercase}}Hello{{/uppercase}} {{#downcase}}World{{/downcase}}'
      });
      return expect(templato.render()).to.be('HELLO world');
    });
  });
  describe('Jade', function() {
    return it('should render jade', function() {
      var templato;
      templato = new Templato;
      templato.registerHelper('downcase', function(arg) {
        return arg.toLowerCase();
      });
      templato.set({
        engine: 'jade',
        template: '!= uppercase("Hello")'
      });
      return expect(templato.render()).to.be('HELLO');
    });
  });
  if (typeof module !== "undefined" && module !== null) {
    return describe('Eco', function() {
      return it('should render eco', function() {
        var templato;
        templato = new Templato;
        templato.registerHelper('downcase', function(arg) {
          return arg.toLowerCase();
        });
        templato.set({
          engine: 'eco',
          template: '<%= @uppercase "Hello" %> <%= @downcase "World" %>'
        });
        return expect(templato.render()).to.be('HELLO world');
      });
    });
  }
});
