// Generated by CoffeeScript 1.3.3
var TemplatoEco;

TemplatoEco = (function() {

  function TemplatoEco() {
    if (!(typeof module !== "undefined" && module !== null)) {
      throw new Error('Eco is available only for Node.js.');
    }
    this.eco = require('eco');
  }

  TemplatoEco.prototype.compile = function(template) {
    return this.eco.compile(template);
  };

  TemplatoEco.prototype.render = function(fn, data) {
    return fn(data);
  };

  return TemplatoEco;

})();

if (typeof module !== "undefined" && module !== null) {
  module.exports = TemplatoEco;
}
