// Generated by CoffeeScript 1.3.3
var TemplatoEJS;

TemplatoEJS = (function() {

  function TemplatoEJS() {
    this.ejs = require('ejs');
  }

  TemplatoEJS.prototype.compile = function(template) {
    return this.ejs.compile(template);
  };

  TemplatoEJS.prototype.render = function(fn, data) {
    return fn(data);
  };

  return TemplatoEJS;

})();

if (typeof module !== "undefined" && module !== null) {
  module.exports = TemplatoEJS;
}
