// Generated by CoffeeScript 1.3.3
var TemplatoJade;

TemplatoJade = (function() {

  function TemplatoJade() {
    this.engine = require('jade');
  }

  TemplatoJade.prototype.compile = function(template) {
    return this.engine.compile(template);
  };

  TemplatoJade.prototype.render = function(fn, data) {
    return fn(data);
  };

  return TemplatoJade;

})();

if (typeof module !== "undefined" && module !== null) {
  module.exports = TemplatoJade;
}
