// Generated by CoffeeScript 1.3.3
var TemplatoMustache;

TemplatoMustache = (function() {

  function TemplatoMustache() {
    this.engine = typeof module !== "undefined" && module !== null ? require('../../vendor/hogan/hogan') : Hogan;
  }

  TemplatoMustache.prototype.compile = function(template) {
    return this.engine.compile(template);
  };

  TemplatoMustache.prototype.render = function(fn, data) {
    return fn.render(data);
  };

  return TemplatoMustache;

})();

if (typeof module !== "undefined" && module !== null) {
  module.exports = TemplatoMustache;
}
